package dev.prabhatpandey.playflix.core.ui.theme
import androidx.compose.ui.graphics.Color

val PlayFlixLightPrimary = Color(0xFFA5D576)
val PlayFlixLightOnPrimary = Color(0xFF0E2000)
val PlayFlixLightPrimaryContainer = Color(0xFFF8FBF3)
val PlayFlixLightOnPrimaryContainer = Color(0xFF0E2000)
val PlayFlixLightSecondary = Color(0xFF8ECDFF)
val PlayFlixLightOnSecondary = Color(0xFF001E30)
val PlayFlixLightSecondaryContainer = Color(0xFFE6F2FF)
val PlayFlixLightOnSecondaryContainer = Color(0xFF001E30)
val PlayFlixLightTertiary = Color(0xFF6E6EC3)
val PlayFlixLightOnTertiary = Color(0xFFFCF8FF)
val PlayFlixLightTertiaryContainer = Color(0xFFE2DFFF)
val PlayFlixLightOnTertiaryContainer = Color(0xFF0E2000)
val PlayFlixLightError = Color(0xFFBA1A1A)
val PlayFlixLightErrorContainer = Color(0xFFFFDAD6)
val PlayFlixLightOnError = Color(0xFFFFFFFF)
val PlayFlixLightOnErrorContainer = Color(0xFF410002)
val PlayFlixLightBackground = Color(0xFFFFFFFF)
val PlayFlixLightOnBackground = Color(0xFF0E2000)
val PlayFlixLightSurface = Color(0xFFFFFFFF)
val PlayFlixLightOnSurface = Color(0xFF0E2000)
val PlayFlixLightSurfaceVariant = Color(0xFFEFFFD9)
val PlayFlixLightOnSurfaceVariant = Color(0xFF0E2000)
val PlayFlixLightOutline = Color(0xFF777680)
val PlayFlixLightInverseOnSurface = Color(0xFFF1EFFF)
val PlayFlixLightInverseSurface = Color(0xFF1E2578)
val PlayFlixLightInversePrimary = Color(0xFFC2C1FF)
val PlayFlixLightShadow = Color(0xFF000000)
val PlayFlixLightSurfaceTint = Color(0xFF5555A9)
val PlayFlixLightOutlineVariant = Color(0xFFC8C5D0)
val PlayFlixLightScrim = Color(0xFF000000)


val PlayFlixDarkPrimary = Color(0xFFA5D576)
val PlayFlixDarkOnPrimary = Color(0xFF0E2000)
val PlayFlixDarkPrimaryContainer = Color(0xFFF8FBF3)
val PlayFlixDarkOnPrimaryContainer = Color(0xFF0E2000)
val PlayFlixDarkSecondary = Color(0xFF8ECDFF)
val PlayFlixDarkOnSecondary = Color(0xFF001E30)
val PlayFlixDarkSecondaryContainer = Color(0xFFE6F2FF)
val PlayFlixDarkOnSecondaryContainer = Color(0xFF001E30)
val PlayFlixDarkTertiary = Color(0xFF6E6EC3)
val PlayFlixDarkOnTertiary = Color(0xFFFCF8FF)
val PlayFlixDarkTertiaryContainer = Color(0xFFE2DFFF)
val PlayFlixDarkOnTertiaryContainer = Color(0xFF0E2000)
val PlayFlixDarkError = Color(0xFFBA1A1A)
val PlayFlixDarkErrorContainer = Color(0xFFFFDAD6)
val PlayFlixDarkOnError = Color(0xFFFFFFFF)
val PlayFlixDarkOnErrorContainer = Color(0xFF410002)
val PlayFlixDarkBackground = Color(0xFF0E2000)
val PlayFlixDarkOnBackground = Color(0xFFEFFFD9)
val PlayFlixDarkSurface = Color(0xFF1B3700)
val PlayFlixDarkOnSurface = Color(0xFFEFFFD9)
val PlayFlixDarkSurfaceVariant = Color(0xFF0E2000)
val PlayFlixDarkOnSurfaceVariant = Color(0xFFEFFFD9)
val PlayFlixDarkOutline = Color(0xFF777680)
val PlayFlixDarkInverseOnSurface = Color(0xFFF1EFFF)
val PlayFlixDarkInverseSurface = Color(0xFF1E2578)
val PlayFlixDarkInversePrimary = Color(0xFFC2C1FF)
val PlayFlixDarkShadow = Color(0xFF000000)
val PlayFlixDarkSurfaceTint = Color(0xFF5555A9)
val PlayFlixDarkOutlineVariant = Color(0xFFC8C5D0)
val PlayFlixDarkScrim = Color(0xFF000000)

val Seed = Color(0xFF020122)